version: "3.8"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    container_name: Angular
    volumes:
      - ./frontend:/usr/app/
      - /usr/app/node_modules
    ports:
      - 4200:4200
    links:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: NestJS
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend:/app/
      - /app/node_modules

  postgres:
    image: postgres:14.5-alpine
    container_name: PostgresSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
    postgres:
      name: db
    